name: tests
on: 
    push: 
    pull_request:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql-version: ['5.7', '8.0']
    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test -e -X --file pom.xml
        env:
          MYSQL_URL: jdbc:mysql://localhost:3306/${{ secrets.MYSQL_DATABASE }}
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    env:
        CI: true
